name: Create Repo
on: 
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the repository to create'
        required: true
        type: string

# env:
#   GH_REPO: ${{ github.inputs.repo_name }}
#   # GH_REPO: "repo-name"
  
jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create repo
        run: echo "${{ github.event.inputs.repo_name }}"
