name: Create Repo
on: 
  workflow_dispatch:
    inputs:
      repo-name: 
        description: 'Name of the repository to be created'
        required: true
        default: ''

env:
  GH_REPO: ${{ github.inputs.repo_name }}
  # GH_REPO: "repo-name"
  
jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create repo
        run: |
          echo "GH_REPO: $GH_REPO"
      
