name: Create Repo
on: 
  workflow_dispatch:
    inputs:
      repo-name: 
        description: 'Name of the repository to be created'
        required: true
        default: ''
jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: echo ${{ github.event.inputs.repo_name }}
        # uses: actions/checkout@v3
